/**
 * Writes `src/clinicZone.bundled.ts`: the clinic zone's offsets from this
 * machine's ICU, for the app to use until a server has sent its own (and for
 * one-phone mode, which never has one). Bundled into the JS, so an OTA update
 * carries a fresh one. `clinicZone.bundled.test.ts` fails when Bun's zone data
 * no longer agrees with it, or when it runs out within a year; run this then.
 *
 *   bun packages/shared/scripts/bundle-clinic-zone.ts
 */
import { join } from 'node:path';
import { zoneSpans } from '../src/zoneSpans.ts';

export const BUNDLED_ZONE = 'Africa/Cairo';
export const BUNDLED_FROM = Date.UTC(2014, 0, 1);

export function bundledUntil(now: Date = new Date()): number {
    return Date.UTC(now.getUTCFullYear() + 6, 0, 1);
}

export function render(until: number): string {
    const { zone, spans } = zoneSpans(BUNDLED_ZONE, BUNDLED_FROM, until);
    const rows = spans.map(
        ([from, offset]) => `        [${from}, ${offset}], // ${new Date(from).toISOString()}`,
    );
    return [
        '// Generated by `bun packages/shared/scripts/bundle-clinic-zone.ts` from Bun’s ICU. Do not edit.',
        "import type { ClinicZone } from './clinicTime.ts';",
        '',
        `export const BUNDLED_CLINIC_ZONE_UNTIL = ${until}; // ${new Date(until).toISOString()}`,
        '',
        'export const BUNDLED_CLINIC_ZONE: ClinicZone = {',
        `    zone: '${zone}',`,
        '    spans: [',
        ...rows,
        '    ],',
        '};',
        '',
    ].join('\n');
}

if (import.meta.main) {
    const path = join(import.meta.dir, '../src/clinicZone.bundled.ts');
    await Bun.write(path, render(bundledUntil()));
    process.stdout.write(`wrote ${path}\n`);
}
